name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: Run eslint scanning

    strategy:
      matrix:
        node-version: [18.x, 19.x, 20.x]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Intsall dependencies
        run: npm install --ignore-scripts --only=dev

      - name: Run lint
        run: npm run lint

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Run test command
        run: echo "test script..."
